#pragma once

#include <cstdint>

enum PacketID : uint8_t {
    ID_INTERNAL_PING = 6,
    ID_PING,
    ID_PING_OPEN_CONNECTIONS,
    ID_CONNECTED_PONG,
    ID_REQUEST_STATIC_DATA,
    ID_CONNECTION_REQUEST,
    ID_AUTH_KEY,
    ID_CONNECTION_REQUEST_ACCEPTED = 16,
    ID_CONNECTION_ATTEMPT_FAILED = 17,
    ID_ALREADY_CONNECTED = 18,
    ID_NEW_INCOMING_CONNECTION = 19,
    ID_NO_FREE_INCOMING_CONNECTIONS = 20,
    ID_DISCONNECTION_NOTIFICATION = 21,
    ID_CONNECTION_LOST = 22,
    ID_RSA_PUBLIC_KEY_MISMATCH = 23,
    ID_CONNECTION_BANNED = 24,
    ID_OUR_SYSTEM_REQUIRES_UNFORGED_ATTESTATION = 25,
    ID_INVALID_PASSWORD = 26,
    ID_MODIFIED_PACKET = 27,
    ID_TIMESTAMP = 28,
    ID_PONG = 29,
    ID_SAMP_PACKET = 40,
    ID_VEHICLE_SYNC = 200,
    ID_AIM_SYNC = 203,
    ID_PLAYER_SYNC = 207,
    ID_RPC = 211
};

enum PacketPriority {
    SYSTEM_PRIORITY,
    HIGH_PRIORITY,
    MEDIUM_PRIORITY,
    LOW_PRIORITY,
    NUMBER_OF_PRIORITIES
};

enum PacketReliability {
    UNRELIABLE,
    UNRELIABLE_SEQUENCED,
    RELIABLE,
    RELIABLE_ORDERED,
    RELIABLE_SEQUENCED
};
